version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Build Project
          command: echo "Building the project..."

  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Run Tests
          command: echo "Running tests..."

  deploy:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install SSH Client
          command: sudo apt-get update && sudo apt-get install -y openssh-client
      - run:
          name: Deploy index.html to Nginx
          command: |
            mkdir -p ~/.ssh
            ssh-keyscan -H 172.26.49.14 >> ~/.ssh/known_hosts
            # Use SSH with a password prompt for SCP
            expect <<EOF
            spawn scp -o StrictHostKeyChecking=no ./index.html root@172.26.49.14:/var/www/html/index.html
            expect "root@172.26.49.14's password:"
            send "$SSH_PASSWORD\r"
            expect eof
EOF
            # Restart Nginx on your localhost using SSH with password
            expect <<EOF
            spawn ssh -o StrictHostKeyChecking=no root@172.26.49.14 "sudo systemctl restart nginx"
            expect "root@172.26.49.14's password:"
            send "$SSH_PASSWORD\r"
            expect eof
EOF

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
